GET HTTP://localhost:8080/api/customers


###

POST HTTP://localhost:8080/api/customers
Content-Type: application/json

{
    "nome": "Patricia Oliveira",
    "cpf": "901.234.567-89",
    "telefone": "(00) 9012-3456",
    "email": "patricia.oliveira@example.com",
    "endereco": "Avenida dos Americas, 36, Centro, Porto Alegre. 70000-567"
}



###

PUT HTTP://localhost:8080/api/customers/8
Content-Type: application/json

{
    
    "nome": "Patricia Oliveira",
    "cpf": "901.234.567-89",
    "telefone": "(00) 9012-3456",
    "email": "patricia@example.com",
    "endereco": "Avenida das Americas, 36, Centro, Porto Alegre. 70000-567"
}

###

DELETE HTTP://localhost:8080/api/customers/9